export default {
  actions: {
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    submit: 'Submit',
    cancel: 'Cancel',
    close: 'Close',
  },
  components: {
    confirm_delete_title: 'Confirmation required',
    confirm_delete_message: 'Are you sure you want to delete this entry?',
    confirm_yes: 'Yes',
    confirm_no: 'No',
    table: {
      no_data: 'Nothing to display',
      no_results: 'Nothing found',
      records: 'No records | 1 record | {total} records',
      query: 'Search...',
      delete: {
        title: 'Confirmation required',
        confirm: 'Are you sure you want to delete this entry?',
      },
    },
    datePicker: {
      placeholder_date: 'Choose a date',
      placeholder_range: 'Choose a period',
      months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      weekdaysMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    },
  },
  errors: {
    error: 'Error',
    access_denied: 'Access Denied',
    http401: 'Error 401: Authorization Required',
    http403: 'Error 403: Access Denied',
    http404: 'Error 404: Not Found',
    http500: 'Error 500: Server Error',
    http0: 'Unknown Error',
  },
}
