export default {
  actions: {
    create: 'Creëren',
    edit: 'Bewerk',
    delete: 'Verwijderen',
    submit: 'Indienen',
    cancel: 'Annuleren',
    close: 'Dichtbij',
  },
  components: {
    confirm_delete_title: 'Bevestiging vereist',
    confirm_delete_message: 'Weet u zeker dat u dit item wilt verwijderen?',
    confirm_yes: 'Ja',
    confirm_no: 'Nee',
    table: {
      no_data: 'Niets om te laten zien',
      no_results: 'Nothing found',
      records: 'Geen records | 1 record | {total} records',
      query: 'Zoeken...',
      columns: {
        id: 'Id',
        created_at: 'Gemaakt bij',
        updated_at: 'Bijgewerkt op',
        actions: 'Acties',
        image: 'Afbeelding',
      },
    },
    datePicker: {
      placeholder_date: 'Kies een datum',
      placeholder_range: 'Kies een periode',
      months: [
        'Januari',
        'Februari',
        'Maart',
        'April',
        'May',
        'June',
        'Juli',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      monthsShort: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
      weekdays: ['Zondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag'],
      weekdaysShort: ['Zo', 'Ma', 'Di', 'Woe', 'Do', 'Vr', 'Za'],
      weekdaysMin: ['Zo', 'Ma', 'Di', 'Woe', 'Do', 'Vr', 'Za'],
    },
  },
  errors: {
    error: 'Fout',
    access_denied: 'Toegang geweigerd',
    http401: 'Error 401: Autorisatie vereist',
    http403: 'Error 403: Toegang geweigerd',
    http404: 'Error 404: Niet gevonden',
    http500: 'Error 500: Serverfout',
    http0: 'Onbekende fout',
  },
}
